### ISSUE TITLE
Explore JGit

### ISSUE THREAD

**Issue by LeeCheryn** [STIW3054/Repo4#17]
Please explore JGit and get some ideas for it. You may refer to https://github.com/centic9/jgit-cookbook. Please search for other useful information related to JGit as well and post them here.

**Comment by LeeCheryn** [comment]
Clone repository using JGit
http://www.codeaffine.com/2015/11/30/jgit-clone-repository/

**Comment by zhamri** [comment]
👍👍

**Comment by Shanthini21** [comment]
Git Clone [Git-ing Started with Git Series]
https://www.youtube.com/watch?v=3MFxb0TNQHQ

**Comment by Tamilarasi95** [comment]
Git commands
http://www.codeaffine.com/2015/12/15/getting-started-with-jgit/
