### ISSUE TITLE
Understand Logger

### ISSUE THREAD

**Issue by LeeCheryn** [STIW3054/Repo4#18]
Please explore and try **Logger**. You may refer to https://examples.javacodegeeks.com/enterprise-java/log4j/log4j-writing-different-log-files-example/ to have a better understanding on Logger. Please refer to https://github.com/STIW3054/Repo4/wiki as well for more information of our project. Please find more useful information about Logger and post it here.

**Comment by LeeCheryn** [comment]
Java Logging: Logger
http://tutorials.jenkov.com/java-logging/logger.html
Class Logger
https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html
Create Log File
https://stackoverflow.com/questions/11258688/create-log-file-for-java-program
Logger in Java
https://www.journaldev.com/977/logger-in-java-logging-example

**Comment by LeongShyeLi** [comment]
```
<dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
```

**log4j.properties**
```
log4j.rootCategory=INFO, file
 
log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=C:\\Users\\Sally Leong\\Desktop\\STIW3054\\LogFiles\\239527.log
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
```

**Source code**
```
package com.uum.rt_project;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

public class testLogger {
    final static Logger logger = Logger.getLogger(testLogger.class);
    
    public static void main(String[] args) {
        PropertyConfigurator.configure("log4j.properties");
        logger.warn("this java file exceed 1 minute in downloading");
    }
}
```

![untitled](https://user-images.githubusercontent.com/31915705/33105365-b42a58bc-cf67-11e7-88ff-4f8995e1d588.png)
